language: shell

sudo: false

git:
  depth: 2

branches:
  only: 
    - master

jobs:
  exclude:
    - if: type = pull_request
  include:
    - stage: Test merge request
      script:
        - echo 'Build starts!!'

